name: Testing case
on:
  push:
    branches:
      - master
      - dev
      - hotfix
  pull_request:
    branches:
      - master
      - dev
      - hotfix
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: "this key is a teting key"
        admin: admin
    steps:
      - uses: actions/checkout@v3
      - name: setup python 3.10.9
        uses: actions/checkout@v3
        with:
          python-version: 3.10.9
      - name: Installl
        run: |
          pip install -r requirements.txt
      - name: Lint8 with flake8
        run: |
          pip install -r requirements.txt
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          coverage run manage.py test
          coverage report
          coverage html
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage report artifact
          path: htmlcov/**
          if-no-files-found: error
          retrention-days: 30
      - name: Django Test
        run: |
          pip install -r requirements.txt
          python manage.py test


